### PR TITLE
Update default.yml based on rubocop rename of Metrics/LineLength

### PR DESCRIPTION
**Pull request by SlakrHakr**

### CODE REVIEW

**Comment by mockdeep** [comment]
Ran into this as well. As of the latest version, the line length rubocop rule displays a violation even though the line is < 80 characters.

**Comment by mockdeep** [comment]
@sds bump on this. We just saw this again on another project.

**Comment by sds** [comment]
This PR wasn't passing CI because it didn't update the Appraisal gemfiles with `appraisal update`. 

Released [0.34.2](https://rubygems.org/gems/haml_lint/versions/0.34.2) with the fix.

**Comment by SlakrHakr** [comment]
> This PR wasn't passing CI because it didn't update the Appraisal gemfiles with `appraisal update`.
> 
> Released [0.34.2](https://rubygems.org/gems/haml_lint/versions/0.34.2) with the fix.

ah, i noticed it was failing in master when i forked it so i wasn't necessarily expecting it to be passing after i made my change.

would have been happy to get the build passing for the pr in any case.

**Pull request closed without merging**
