### PR TITLE
Support haml 5.1

### PR DESCRIPTION
**Pull request by jaredbeck**
Let's see if CI passes 😈

If more work is necessary, I'll be happy to do what I can, just wanted to yolo-run CI first.

### CODE REVIEW

**Comment by jaredbeck** [comment]
doh, i think i need to edit `gemfiles/haml5.gemfile` sorry .. just a sec

**Comment by jaredbeck** [comment]
[CI passes](https://travis-ci.org/sds/haml-lint/builds/535059784) on haml 5.1

**Comment by jaredbeck** [comment]
Thanks Michael. Changes made.

**Comment by sds** [comment]
I merged the change through GitHub, but looks like it got buggy and didn't mark this PR as merged. Closing this PR as it's now showing rebase conflicts since it was technically already merged.

Thanks for the contribution, @jaredbeck!

**Comment by jaredbeck** [comment]
> I merged the change through GitHub, but looks like it got buggy and didn't mark this PR as merged. 

It's been kind of slow and flaky for me today, also.

**Pull request closed without merging**
